package io.f1r3fly.f1r3drive.folders;

import io.f1r3fly.f1r3drive.blockchain.BlockchainContext;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.time.Instant;
import java.util.Properties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Base class for physical wallet folders on disk.
 * Provides common functionality for both locked and unlocked wallet states.
 */
public abstract class PhysicalWallet implements WalletOperations {

    private static final Logger LOGGER = LoggerFactory.getLogger(
        PhysicalWallet.class
    );

    protected final BlockchainContext blockchainContext;
    protected final Path walletPath;
    protected final String baseDirectory;

    // Standard file names used in wallet folders
    protected static final String WALLET_INFO_FILE = ".wallet_info";
    protected static final String README_FILE = "README.md";
    protected static final String TOKENS_DIR = "tokens";
    protected static final String FOLDERS_DIR = "folders";
    protected static final String BLOCKCHAIN_FILES_DIR = "blockchain_files";

    public PhysicalWallet(
        BlockchainContext blockchainContext,
        Path walletPath,
        String baseDirectory
    ) {
        this.blockchainContext = blockchainContext;
        this.walletPath = walletPath;
        this.baseDirectory = baseDirectory;
    }

    /**
     * Gets the REV address for this wallet
     */
    public String getRevAddress() {
        return blockchainContext.getWalletInfo().revAddress();
    }

    /**
     * Gets the file system path to this wallet's folder
     */
    public Path getWalletPath() {
        return walletPath;
    }

    /**
     * Gets the blockchain context for this wallet
     */
    public BlockchainContext getBlockchainContext() {
        return blockchainContext;
    }

    /**
     * Creates the basic wallet folder structure that is common to all wallet types
     */
    protected void createBasicFolderStructure() throws IOException {
        // Create main wallet directory
        if (!Files.exists(walletPath)) {
            Files.createDirectories(walletPath);
            LOGGER.debug("Created wallet directory: {}", walletPath);
        }

        // Create subdirectories
        createSubDirectory(TOKENS_DIR);
        createSubDirectory(FOLDERS_DIR);
        createSubDirectory(BLOCKCHAIN_FILES_DIR);

        // Create wallet info file
        createWalletInfoFile();

        // Create README file
        createReadmeFile();
    }

    /**
     * Creates a subdirectory within the wallet folder (internal method)
     */
    protected Path createSubDirectory(String dirName) throws IOException {
        Path dirPath = walletPath.resolve(dirName);
        if (!Files.exists(dirPath)) {
            Files.createDirectories(dirPath);
            LOGGER.debug("Created directory: {}", dirPath);
        }
        return dirPath;
    }

    /**
     * Creates the wallet info metadata file
     */
    protected void createWalletInfoFile() throws IOException {
        Path infoPath = walletPath.resolve(WALLET_INFO_FILE);

        Properties props = new Properties();
        props.setProperty("wallet.address", getRevAddress());
        props.setProperty("wallet.created", Instant.now().toString());
        props.setProperty("wallet.type", this.getClass().getSimpleName());
        props.setProperty("wallet.status", getWalletStatus());

        try (
            var writer = Files.newBufferedWriter(
                infoPath,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING
            )
        ) {
            props.store(writer, "F1r3Drive Physical Wallet Information");
        }

        LOGGER.debug("Created wallet info file: {}", infoPath);
    }

    /**
     * Creates a README file explaining the wallet structure
     */
    protected void createReadmeFile() throws IOException {
        Path readmePath = walletPath.resolve(README_FILE);

        String readmeContent = String.format(
            """
            # Wallet %s

            This folder contains the physical representation of REV wallet address: `%s`

            ## Folder Structure
            - `%s/` - Token files and balances
            - `%s/` - Sub-folders and their contents
            - `%s/` - Files stored on the blockchain
            - `%s` - Wallet metadata and configuration

            ## Status
            Wallet Status: %s
            Created: %s

            Generated by F1r3Drive Physical Wallet System
            """,
            getRevAddress(),
            getRevAddress(),
            TOKENS_DIR,
            FOLDERS_DIR,
            BLOCKCHAIN_FILES_DIR,
            WALLET_INFO_FILE,
            getWalletStatus(),
            Instant.now().toString()
        );

        Files.write(
            readmePath,
            readmeContent.getBytes(),
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING
        );
        LOGGER.debug("Created README file: {}", readmePath);
    }

    /**
     * Gets the current status of this wallet (locked/unlocked/etc)
     */
    public abstract String getWalletStatus();

    /**
     * Creates the specific folder structure for this wallet type
     */
    public abstract void createFolderStructure() throws IOException;

    /**
     * Cleans up resources when the wallet is no longer needed
     */
    public abstract void cleanup();

    /**
     * Gets the path to the tokens directory
     */
    public Path getTokensDirectory() {
        return walletPath.resolve(TOKENS_DIR);
    }

    /**
     * Gets the path to the folders directory
     */
    public Path getFoldersDirectory() {
        return walletPath.resolve(FOLDERS_DIR);
    }

    /**
     * Gets the path to the blockchain files directory
     */
    public Path getBlockchainFilesDirectory() {
        return walletPath.resolve(BLOCKCHAIN_FILES_DIR);
    }

    /**
     * Checks if this wallet's folder exists on disk
     */
    public boolean exists() {
        return Files.exists(walletPath) && Files.isDirectory(walletPath);
    }

    /**
     * Checks if this wallet is currently locked (read-only access)
     */
    public boolean isLocked() {
        return "LOCKED".equals(getWalletStatus());
    }

    /**
     * Checks if this wallet is currently unlocked (full access)
     */
    public boolean isUnlocked() {
        return "UNLOCKED".equals(getWalletStatus());
    }

    /**
     * Validates that wallet operations are permitted
     * @throws IllegalStateException if the wallet is locked and operation requires unlock
     */
    protected void requireUnlocked() throws IllegalStateException {
        if (isLocked()) {
            throw new IllegalStateException(
                String.format(
                    "Operation not permitted on locked wallet %s. Please unlock the wallet first with the private key.",
                    getRevAddress()
                )
            );
        }
    }

    /**
     * Validates that read operations are permitted (allowed for both locked and unlocked)
     */
    protected void requireReadAccess() {
        // Read access is allowed for both locked and unlocked wallets
        // This method exists for consistency and future expansion
    }

    @Override
    public String toString() {
        return String.format(
            "%s{address=%s, path=%s, status=%s}",
            this.getClass().getSimpleName(),
            getRevAddress(),
            walletPath,
            getWalletStatus()
        );
    }

    // Abstract methods that must be implemented by subclasses
    // These provide the actual implementation of WalletOperations

    /**
     * Abstract method for file creation - implementation depends on wallet state
     */
    public abstract void createFile(String relativePath, byte[] content)
        throws IOException, IllegalStateException;

    /**
     * Abstract method for file writing - implementation depends on wallet state
     */
    public abstract void writeFile(String relativePath, byte[] content)
        throws IOException, IllegalStateException;

    /**
     * Abstract method for file reading - implementation depends on wallet state
     */
    public abstract byte[] readFile(String relativePath) throws IOException;

    /**
     * Abstract method for file deletion - implementation depends on wallet state
     */
    public abstract void deleteFile(String relativePath)
        throws IOException, IllegalStateException;

    /**
     * Abstract method for file renaming - implementation depends on wallet state
     */
    public abstract void renameFile(String oldPath, String newPath)
        throws IOException, IllegalStateException;

    /**
     * Abstract method for directory creation - implementation depends on wallet state
     */
    public abstract void createDirectory(String relativePath)
        throws IOException, IllegalStateException;

    /**
     * Abstract method for directory deletion - implementation depends on wallet state
     */
    public abstract void deleteDirectory(String relativePath)
        throws IOException, IllegalStateException;

    /**
     * Abstract method for directory listing - implementation depends on wallet state
     */
    public abstract String[] listDirectory(String relativePath)
        throws IOException;

    /**
     * Abstract method for directory renaming - implementation depends on wallet state
     */
    public abstract void renameDirectory(String oldPath, String newPath)
        throws IOException, IllegalStateException;

    /**
     * Abstract method for file existence check - implementation depends on wallet state
     */
    public abstract boolean fileExists(String relativePath);

    /**
     * Abstract method for directory check - implementation depends on wallet state
     */
    public abstract boolean isDirectory(String relativePath);

    /**
     * Abstract method for token balance update - implementation depends on wallet state
     */
    public abstract void updateTokenBalance(String tokenName, long balance)
        throws IOException, IllegalStateException;

    /**
     * Abstract method for blockchain transaction execution - implementation depends on wallet state
     */
    public abstract void executeBlockchainTransaction(String transactionData)
        throws IllegalStateException;
}
